name: js-sdks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build + Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: yarn install
        run: yarn install

      - name: yarn playwright install
        run: yarn playwright install --with-deps
        working-directory: ./packages/js-client-core

      - name: yarn build
        run: yarn build

      - name: yarn lint
        run: yarn lint

      - name: yarn test
        run: yarn test
