name: Release @configdirector/react-native-sdk

on:
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: write # Required to tag the released commit

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/prepare-release-build
        with:
          needs_playwright: 'true'

      - run: yarn release
        working-directory: ./packages/react-native-sdk

      - name: Tag release
        uses: ./.github/actions/tag-release
        with:
          package_dir: packages/react-native-sdk
          github_token: ${{ github.token }}
