name: Release @configdirector/react-web-sdk

on:
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: ./.github/actions/prepare-release-build

      - run: yarn playwright install --with-deps
        working-directory: ./packages/js-client-core

      - run: yarn release
        working-directory: ./packages/react-web-sdk
